/**:
  ros__parameters:
    namespace: "unitree_go1"
    
    # UDP parameters
    dt_send: 0.0004              # Send period [s]
    dt_recv: 0.0004              # Receive period [s]

    sdk_cmd_topic: "low_cmd"          # Topic to subscribe for velocity commands
    odom_topic: "odom"
    publish_odom_tf: true             # Whether to publish odometry transform

    # ==== Subscribers ====
    cmd_vel_topic: "cmd_vel"
    cmd_vel_timeout: 0.5
    low_state_timeout_sec: 0.1

    # ==== Publishers ====

    # IMU
    imu_frequency: 1000.0             # IMU frequency [Hz]
    imu_topic: "imu"

    # Joint States
    joint_states_frequency: 500.0      # Joint states frequency [Hz]
    joint_states_topic: "joint_states"

    # Remote Joystick
    remote_frequency: 100.0           # Remote frequency [Hz]
    remote_topic: "remote"
