%YAML:1.0

unitree_camera_interface:
   namespace: "unitree_go1"     # Node namespace
   width: 1856                  # Image raw width 
   height: 800                  # Image raw height
   fps: 30                      # Image raw fps  
   format: "MJPEG"              # YUYV | MJPEG 
   force_v4l2: true             # Force using v4l2 driver
   disable_gstreamer: true      # Disable gstreamer pipeline
   disable_opencl: true         # Disable opencl acceleration
   opencv_videoio_debug: true   # Enable opencv videoio debug info

   # Information of the Unitree Camera from the old SDK
   unitree_camera:
      ip: "192.168.123.15"
      port: 9201
      device_id: 2
      node_id: 0                # Is the index for \dev\videoX can be 1 or 2 
      camera_name:              # Name of the camera
      camera_frame:             # Frame of the camera
      # Camera info url for camera calibration data
      camera_info_url:          